// Text content lookup
const textTable = {
  1: "Education is very important for the growth of a country. It helps people learn new things, gain knowledge, and become successful in life. In India, the government has made many rules and plans to improve education. One such important plan is the National Education Policy. The National Education Policy is a set of rules made by the Indian government to improve education in schools and colleges. The first education policy in India was made in 1968. After many years, a new policy was made in 2020. This new policy aims to make learning better and more useful for students. The new policy focuses on making education fun and interesting. It wants children to enjoy learning rather than just memorizing things. The policy suggests that small children should learn in their own mother tongue or local language. This will help them understand lessons better. The policy also says that students should not be forced to learn many subjects at once. Instead, they should have choices and be able to learn what they like. Earlier, schools in India followed a system where ten years of school was followed by two years of higher secondary education. The new policy changes this system. In this new system, the first five years are for very young children, where they mostly learn through fun activities. The next three years are for learning basic subjects. The following three years focus on deeper knowledge, and the last four years prepare students for college and work life. This way, children get more time to understand and learn at their own pace. The National Education Policy also gives importance to practical learning. It says that students should not just read books but also do activities to understand things better. For example, instead of just reading about plants, students should go outside and observe them. Instead of only reading about math, they should solve real problems using numbers. This will help them think better and become creative. The policy also suggests that students should learn skills like painting, music, sports, and coding, so they can explore different career options in the future. One major change in the new policy is that students will not have to study only Science, Commerce, or Arts in higher classes. Earlier, students had to choose one of these streams and study only those subjects. But now, they can mix subjects. A student who likes science can also study music, and a student who likes commerce can also learn coding. This gives more freedom to students and helps them learn what they truly enjoy. Examinations are also made simpler in the new policy. Earlier, students had to study a lot and remember many things just to pass exams. Now, exams will focus more on checking how much students understand rather than how much they memorize. Students will also get report cards that not only show their marks but also talk about their talents and interests. Teachers, classmates, and even students themselves can write about their progress in these report cards. Teachers play a very important role in education. The National Education Policy aims to improve the quality of teachers. It suggests better training programs for teachers so that they can teach in a better way. It also says that teachers should be respected and paid well, so more people choose teaching as a career. When teachers are happy and skilled, students will also learn better. Higher education is also improved through this policy. Colleges and universities will offer more flexible courses. Students can enter and leave courses at different times. If a student studies for one year, they will get a certificate. If they study for two years, they will get a diploma. If they complete three or four years, they will get a degree. This way, students will not feel pressured and can study at their own pace. The policy also plans to open more good colleges and research centres in different parts of India, so every student gets a chance to study in a good institution. Technology is another important part of the National Education Policy. The policy suggests that online learning should be improved. Many students cannot go to school every day due to various reasons. Online classes, digital books, and educational videos can help such students learn from home. The policy also plans to provide better internet and computer facilities to schools, especially in villages, so that every child can benefit from technology. The National Education Policy also aims to make education available to everyone. In India, many children do not go to school because of poverty or other reasons. The policy wants to help such children by providing free education and food in schools. It also focuses on the education of girls and children with disabilities. The aim is to make sure that every child, no matter where they come from, gets the opportunity to learn and grow.",
  2: "Natural disasters are events that cause great damage to life, property, and the environment. These disasters can happen suddenly and affect millions of people. India is a large country with different types of land, weather, and climate, which makes it prone to many natural disasters. Some of the most common disasters in India include floods, earthquakes, cyclones, droughts, and landslides. These disasters cause loss of human and animal lives, destroy houses, damage crops, and affect the economy. Although natural disasters cannot be stopped, their impact can be reduced by taking preventive measures and preparing for them in advance. Floods are one of the most common natural disasters in India. They occur when there is too much rainfall, causing rivers and lakes to overflow. Sometimes, floods are also caused by the sudden release of water from dams. Many cities and villages get submerged in water, leading to loss of lives, destruction of houses, and damage to roads and bridges. Floods also bring diseases, as dirty water spreads infections. To reduce the impact of floods, the government has built dams and embankments to control water flow. Warning systems have been set up to inform people in advance so that they can move to safer places. Earthquakes are another serious natural disaster that affects different parts of India. An earthquake happens when there is a sudden movement in the Earth's crust. This movement releases energy in the form of shaking, which can be very strong and cause buildings to collapse. Some areas in India, such as Gujarat and the northeastern states, are more prone to earthquakes. Major earthquakes in the past, such as the Gujarat earthquake in 2001, have caused great destruction. To reduce the damage caused by earthquakes, buildings should be designed to withstand strong shaking. People should be educated on safety measures, such as taking cover under strong furniture or standing in doorways during an earthquake. Early warning systems should be improved so that people get time to evacuate. Cyclones can destroy houses, uproot trees, damage power lines, and flood entire villages. They also cause sea waves to rise, which leads to coastal flooding. In recent years, the government has set up early warning systems to alert people before a cyclone arrives. Cyclone shelters have been built in coastal areas where people can take refuge. Planting more trees along coastlines also helps reduce the impact of strong winds. Fishermen are warned in advance to avoid going to sea when a cyclone is approaching. Droughts occur when there is very little or no rainfall for a long time. This leads to a shortage of water for drinking, farming, and daily use. Many states in India face droughts frequently. When there is no water, crops fail, and farmers suffer huge losses. People and animals struggle to get enough drinking water. To prevent droughts, rainwater harvesting should be encouraged so that water can be stored for future use. More trees should be planted to attract rainfall and prevent soil from drying up. Farmers should use modern irrigation techniques like drip irrigation, which saves water. Water conservation should be practiced by everyone to avoid wastage. Landslides are another major natural disaster that occurs mostly in hilly regions. A landslide happens when rocks and soil slide down a mountain or hill due to heavy rain, earthquakes, or construction activities. One of the worst cases of land sinking happened in Uttarakhand, where the ground started cracking due to excessive construction and environmental damage. Landslides block roads, destroy houses, and make travel difficult. To reduce landslides, trees should not be cut down on hillsides, as their roots help hold the soil together. Construction in hilly areas should be controlled, and proper drainage systems should be built to prevent water from loosening the soil. Tsunamis are giant sea waves caused by underwater earthquakes or volcanic eruptions. They can hit coastal areas suddenly and wash away everything in their path. The 2004 tsunami in the Indian Ocean caused huge destruction in coastal areas of India. Thousands of people lost their lives, and entire villages were wiped out. To reduce the impact of tsunamis, early warning systems have been installed along coastal regions. People living near the sea should be trained on what to do in case of a tsunami warning. Coastal forests and mangroves should be protected, as they act as natural barriers against strong waves. Forest fires are another natural disaster that affects India. Fires spread quickly in dry forests, destroying trees, killing wildlife, and polluting the air. Many times, forest fires are caused by human activities, such as throwing burning cigarettes or leaving campfires unattended. Strong winds make the fires spread faster. To prevent forest fires, people should be careful when lighting fires in forests. Firewatch towers and satellite monitoring systems should be used to detect fires early and stop them before they spread.",
  3: "",
  4: "",
  5: "", 
6: "",
7: "",
8: "",
9: "",
10: "",
11: "This is the transcription text.",
12: "This is the transcription text.",
13: "This is the transcription text.",
14: "This is the transcription text.",
15: "This is the transcription text.",
16: "This is the transcription text.",
17: "This is the transcription text.",
18: "This is the transcription text.",
19: "This is the transcription text.",
20: "This is the transcription text.",
21: "This is the transcription text.",
22: "This is the transcription text.",
23: "This is the transcription text.",
24: "This is the transcription text.",
25: "This is the transcription text.",
26: "This is the transcription text.",
27: "This is the transcription text.",
28: "This is the transcription text.",
29: "This is the transcription text.",
30: "This is the transcription text.",
31: "This is the transcription text.",
32: "This is the transcription text.",
33: "This is the transcription text.",
34: "This is the transcription text.",
35: "This is the transcription text.",
36: "This is the transcription text.",
37: "This is the transcription text.",
38: "This is the transcription text.",
39: "This is the transcription text.",
40: "This is the transcription text.",
41: "This is the transcription text.",
42: "This is the transcription text.",
43: "This is the transcription text.",
44: "This is the transcription text.",
45: "This is the transcription text.",
46: "This is the transcription text.",
47: "This is the transcription text.",
48: "This is the transcription text.",
49: "This is the transcription text.",
50: "This is the transcription text.",
51: "This is the transcription text.",
52: "This is the transcription text.",
53: "This is the transcription text.",
54: "This is the transcription text.",
55: "This is the transcription text.",
56: "This is the transcription text.",
57: "This is the transcription text.",
58: "This is the transcription text.",
59: "This is the transcription text.",
60: "This is the transcription text.",
61: "This is the transcription text.",
62: "This is the transcription text.",
63: "This is the transcription text.",
64: "This is the transcription text.",
65: "This is the transcription text.",
66: "This is the transcription text.",
67: "This is the transcription text.",
68: "This is the transcription text.",
69: "This is the transcription text.",
70: "This is the transcription text.",
71: "This is the transcription text.",
72: "This is the transcription text.",
73: "This is the transcription text.",
74: "This is the transcription text.",
75: "This is the transcription text.",
76: "This is the transcription text.",
77: "This is the transcription text.",
78: "This is the transcription text.",
79: "This is the transcription text.",
80: "This is the transcription text.",
81: "This is the transcription text.",
82: "This is the transcription text.",
83: "This is the transcription text.",
84: "This is the transcription text.",
85: "This is the transcription text.",
86: "This is the transcription text.",
87: "This is the transcription text.",
88: "This is the transcription text.",
89: "This is the transcription text.",
90: "This is the transcription text.",
91: "This is the transcription text.",
92: "This is the transcription text.",
93: "This is the transcription text.",
94: "This is the transcription text.",
95: "This is the transcription text.",
96: "This is the transcription text.",
97: "This is the transcription text.",
98: "This is the transcription text.",
99: "This is the transcription text.",
100: "This is the transcription text.",

};
